// This file is auto-generated by scripts/generate-plugin-registry.mjs
// Do not edit manually!

/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-return */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */

import type { CloudExtension, CloudExtensionManifest } from '@n8n/extension-sdk/frontend';

export interface ExtensionDefinition {
	name: string;
	resolvedName: string;
	module: { default: CloudExtension };
	shouldLoad?: () => Promise<boolean>;
	extensionPoints: string[];
	manifest: CloudExtensionManifest;
}

export const EXTENSIONS: ExtensionDefinition[] = [];
